name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-13"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDdlZmE1NzMtZDhkYS00OGJmLThhNDMtOWNkNjFmNDY4NDVhIiwidGVuYW50X2lkIjoiMWUzODQzYTU0NTE4YTJjYjE1OTdjNDVkOGM2ZTdlZjJmMGZhZmM4NDQ5ZGZmYzdkYWRlMjg3NjcxODE0MDdiYyIsImludGVybmFsX3NlY3JldCI6IjU1M2NhMWRlLTlmNWYtNGQ1OS1iZTE1LTBiNWRiOWQ5ZGI2OSJ9.ERL7_M0WkFK6VUDagiRtc434p6YH3smLt26V2tyBjCc"
JWT_SECRET='SUPER_SECRETE'
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1